---
abstract: 'Hatena auth integration for Amon2'
author:
  - 'Kentaro Kuribayashi <kentarok@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2-Auth-Site-Hatena
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Amon2::Auth: 0.01
  JSON: 2.53
  Mouse: 0.97
  OAuth::Lite: 1.31
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
